### ISSUE TITLE
[Bug] S2 P1 - Build failed after manually cancelling ExaminationApplication.main()

### ISSUE THREAD

**Issue by asirbescu-fhbg** [asirbescu-fhbg/fh-burgenland-bswe-3b-2at#9]
### Description

The ExaminationApplication.main() method can initially be executed without errors. After a manual stop, however, the following error occurs:

```
Execution failed for task ':ExaminationApplication.main()'.
> Build cancelled while executing task ':ExaminationApplication.main()'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 52s
3 actionable tasks: 1 executed, 2 up-to-date
```

Java version: Oracle OpenJDK 21
Gradle version: 8.5 (`gradle-wrapper.properties: distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip`)
IntelliJ-IDEA version: IntelliJ IDEA 2023.3.3 (Community Edition)
OS: Windows

### Severity

S2 - Major Bug

### Priority

P1 - High

### To Reproduce

1. Run ExaminationApplication.main() method via IntelliJ 
2. Stop ExaminationApplication.main() method via IntelliJ 
3. Error message appears

### Expected behavior

No error message should appear. Build should succeed.

### Screenshots

Last messages from the ExaminationApplication.main() run:

![image](https://github.com/asirbescu-fhbg/fh-burgenland-bswe-3b-2at/assets/114183627/10ff9548-04ca-416d-94c4-89ab6f3a99f9)

Error message:
![image](https://github.com/asirbescu-fhbg/fh-burgenland-bswe-3b-2at/assets/114183627/447a0ebb-7706-40a2-b53a-dbb5637515d0)

IntelliJ project setting - Build tools:
![grafik](https://github.com/asirbescu-fhbg/fh-burgenland-bswe-3b-2at/assets/114183627/9da83d4b-bce1-4917-bc5b-9053f9864ba3)

### Additional Information

Some on the Internet claim that this is not an error but only a warning (although the build fails). 

Already tried the following:
- Clean project
- Rebuild project

This appears after executing the command `gradle build --warning-mode all`:
```
19:56:48: Executing 'build --warning-mode all'...

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :resolveMainClassName
> Task :bootJar
> Task :jar
> Task :assemble
> Task :checkstyleMain UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :checkstyleTest UP-TO-DATE

> Task :test
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_framework_implementation_dependencies

Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :test

PersonControllerTest > testGetById() PASSED

PersonServiceImplTest > testGetById() PASSED

2024-02-07T19:56:56.637+01:00  INFO 12692 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2024-02-07T19:56:56.641+01:00  INFO 12692 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-02-07T19:56:56.646+01:00  INFO 12692 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

> Task :check
> Task :build

BUILD SUCCESSFUL in 8s
9 actionable tasks: 4 executed, 5 up-to-date
19:56:56: Execution finished 'build --warning-mode all'.
```

**Comment by muhlba91** [comment]
can you please run the following gradle commands via the command line and IntelliJ plugin (there should be a sidebar where you can select which command to run):
- `build`
- `bootRun`
- `bootJar`

let me know the outcome of that!

in general, i'd suggest that if the command line versions run through without a failure (yes, the deprecation warnings you can ignore), all is good. if the IntelliJ plugin runs with an error but only when stopping the application, it should also be fine. then, the plugin might perform some additional action or interpret the warning as a failure... from the setup, it looks good.

take care, though, because directly running the `main` method of the `ExaminationApplication` sometimes led to errors in the past (IDEs sometimes performed some weird classpath addition or so which was incompatible with Spring Boot); hence, i'd suggest trying to use the Gradle plugin directly.

**Comment by asirbescu-fhbg** [comment]
### Partial result of running command `gradle build` via the IntelliJ plugin:

```
18:45:39: Executing 'build'...
Starting Gradle Daemon...
Gradle Daemon started in 1 s 26 ms
...
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
...
BUILD SUCCESSFUL in 13s
9 actionable tasks: 3 executed, 6 up-to-date
18:45:54: Execution finished 'build'.
```

### Partial result of running command `.\gradlew build` via the command line:
```
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :test FAILED
...
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
...
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
...
BUILD FAILED in 9s
9 actionable tasks: 6 executed, 3 up-to-date
```
(Content failed test report: [build_test_fail_report.txt](https://github.com/asirbescu-fhbg/fh-burgenland-bswe-3b-2at/files/14212997/build_test_fail_report.txt))


### Partial result of running command `gradle bootRun` via the IntelliJ plugin (results are the same as running the `ExaminationApplication.main()` method):
After starting ...
```
19:06:18: Executing 'bootRun'...

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :resolveMainClassName UP-TO-DATE

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.2)

2024-02-08T19:21:48.675+01:00  INFO 27000 --- [  restartedMain] i.m.f.s.e.ExaminationApplication         : Starting ExaminationApplication using Java 21.0.2 with PID 27000
...
```
After stopping ...
```
Execution failed for task ':bootRun'.
> Build cancelled while executing task ':bootRun'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 1m 49s
4 actionable tasks: 1 executed, 3 up-to-date
```

### Partial result of running command `.\gradlew bootRun` via the command line:
```
> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.2)

2024-02-08T19:09:59.918+01:00  INFO 16136 --- [  restartedMain] i.m.f.s.e.ExaminationApplication         : Starting ExaminationApplication using Java 21.0.2 with PID 16136
...
<==========---> 80% EXECUTING [13s]
<==========---> 80% EXECUTING [8m 9s]
```

### Partial result of running command `gradle bootJar` via the IntelliJ plugin: 
```
19:20:06: Executing 'bootJar'...

> Task :compileJava UP-TO-DATE
> Task :processResources
> Task :classes
> Task :resolveMainClassName UP-TO-DATE
> Task :bootJar

BUILD SUCCESSFUL in 3s
4 actionable tasks: 2 executed, 2 up-to-date
19:20:10: Execution finished 'bootJar'.
```

### Partial result of running command `.\gradlew bootJar` via the command line:
```
BUILD SUCCESSFUL in 4s
4 actionable tasks: 2 executed, 2 up-to-date
```

@muhlba91 Most of the builds went through successfully, one failed because of the tests. Can I nevertheless assume that it works overall?

**Comment by muhlba91** [comment]
yes, i agree. i think it's good to continue as it is - i'd advice to sometimes execute `clean` if you face an error again.
if that issue pops up again in any important case (e.g. pipeline), please ping again. 😀 

you can close this issue and reopen it if needed, or leave it open. as you wish.
